### ISSUE TITLE
Option to translate "backspace" key to CTRL-H

### ISSUE THREAD

**Issue by wootpthomas** [cminyard/ser2net#32] opened 2020-08-31 17:37 UTC
We have ser2net running on a single board computer (SBC- https://libre.computer/products/boards/roc-rk3328-cc/ running Debuan Buster from this armbian image: https://www.armbian.com/renegade/

When anyone telnets to a serial device hosted on the SBC, they are unable to use the "backspace" key and have to instead use CTRL-H. Som programs like Minicom have a feature to turn on the auto-translation of BS to CTRL-H. Would ser2net be able to also provide this feature? I would think that adding this feature would be fairly simple.

I've spent countless hours trying to tinker around with `stty` settings on both my client PC and the SBC running ser2net without any luck. It would be awesome to be able to enable this with an addition to the config file.

**Comment by cminyard** [comment] 2020-08-31 18:31
On Mon, Aug 31, 2020 at 10:37:51AM -0700, wootpthomas wrote:
> We have ser2net running on a single board computer (SBC- https://libre.computer/products/boards/roc-rk3328-cc/ running Debuan Buster from this armbian image: https://www.armbian.com/renegade/
> 
> When anyone telnets to a serial device hosted on the SBC, they are unable to use the "backspace" key and have to instead use CTRL-H. Som programs like Minicom have a feature to turn on the auto-translation of BS to CTRL-H. Would ser2net be able to also provide this feature? I would think that adding this feature would be fairly simple.
> 
> I've spent countless hours trying to tinker around with `stty` settings on both my client PC and the SBC running ser2net without any luck. It would be awesome to be able to enable this with an addition to the config file.

Hmm.  This is kind of a hard thing to provide in ser2net.

Minicom can do this because it is a terminal emulator, and thus it can
send anything it likes when you hit the backspace key.  By default a
backspace will send a 0x7f character, but Minicom lets you change what
happens when you hit the backspace key.

No amount of messing with stty is going to fix this because the problem
is not on the SBC or the host line discipline.  The problem is on
whatever is on the other end of the serial port line, which you do not
name.  If it interpreted 0x7f as backspace, then all would be fine.

That would be my first suggestion.  That way the problem is solved no
matter what you use for connection, and you don't have to mess around
with Minicom's configuration or whatnot.  It would just work.

Of course, that may not be possible in your situation.  But you can also
configure your terminal emulator on the host to send ^H on a backspace.
Simply go to the preferences of your terminal, and under "Compatibility"
you can have it send what you need for a backspace key.

There are other ways, like writing a little script to translate the
characters in front of telnet, but that's probably not necessary.

I am loath to change this in ser2net because it's not really ser2net's
job.  I think the options above will serve you better.

-corey

**Comment by cminyard** [comment] 2020-08-31 21:11
Closing, reopen if you still need this.

**Closed by cminyard** 2020-08-31 21:11 UTC
