### ISSUE TITLE
python serial error "timeout while waiting for option 'purge'" with ser2net v4.6

### ISSUE THREAD

**Issue by ffolkes1911** [cminyard/ser2net#116] opened 2024-02-01 12:29 UTC
Hi,

we've been using `ser2net` v4.5 and connecting with python serial code for some time, everything was working fine. Today I setup another computer, but during this setup I pulled latest `ser2net` ~~version 4.6~~ (EDIT: It was latest commit from main branch, so technically might be newer than the 4.6 release, not sure). Using this latest version when I try to connect using python telnet, I get error:  
```
 File ".../src/pts_packages/serial_operations.py", line 58, in serial_connect
    self.CONN = serial.serial_for_url(
  File ".../.ptsenv/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 493, in open
    self.reset_input_buffer()
  File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 647, in reset_input_buffer
    self.rfc2217_send_purge(PURGE_RECEIVE_BUFFER)
  File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 876, in rfc2217_send_purge
    item.wait(self._network_timeout)  # wait for acknowledge from the server
  File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 362, in wait
    raise SerialException("timeout while waiting for option {!r}".format(self.name))
serial.serialutil.SerialException: timeout while waiting for option 'purge'
```
Tried two different USB FTDI devices, and both fail same way ~~on v4.6~~ latest ser2net, and work fine on v4.5. Only tried on one computer so far. Connection in config `yaml` file looks like this:  
```
connection: &con01
  accepter: telnet(rfc2217),tcp,33032
  connector: serialdev,/dev/h32,115200n81,local
  enable: on
  timeout: 1800
  options:
    max-connections: 5
```

During setup I pull latest `gensio` and `ser2net` from github, and build them locally, because apt has old versions. No additional options or workarounds are being done, building with just `./reconf && ./configure && make && sudo make install`. I can also connect to v4.6 fine when using CLI `telnet <host> <post>`, so maybe python lib is at fault? But it works with older `ser2net` version, so I'm trying here first.

Serial port itself can be accessed by user without `sudo` and `ser2net` daemon is also reconfigured to run as a user daemon.

OS: Ubuntu 22.04.3 LTS
gensio: 2.8.2
Python: 3.10.12
Python serial lib: 3.5

**Comment by cminyard** [comment] 2024-02-01 13:25
On Thu, Feb 01, 2024 at 04:29:35AM -0800, ffolkes1911 wrote:
> Hi,
> 
> we've been using `ser2net` v4.5 and connecting with python serial code for some time, everything was working fine. Today I setup another computer, but during this setup I pulled latest `ser2net` version 4.6. Using this latest version when I try to connect using python telnet, I get error:  
> ```
>  File ".../src/pts_packages/serial_operations.py", line 58, in serial_connect
>     self.CONN = serial.serial_for_url(
>   File ".../.ptsenv/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
>     instance.open()
>   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 493, in open
>     self.reset_input_buffer()
>   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 647, in reset_input_buffer
>     self.rfc2217_send_purge(PURGE_RECEIVE_BUFFER)
>   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 876, in rfc2217_send_purge
>     item.wait(self._network_timeout)  # wait for acknowledge from the server
>   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 362, in wait
>     raise SerialException("timeout while waiting for option {!r}".format(self.name))
> serial.serialutil.SerialException: timeout while waiting for option 'purge'
> ```

What is the gensio version where it works?  The problem is probably not
in ser2net, it's probably in the gensio library.

-corey

**Comment by cminyard** [comment] 2024-02-01 16:23
On Thu, Feb 01, 2024 at 07:25:55AM -0600, Corey Minyard wrote:
> On Thu, Feb 01, 2024 at 04:29:35AM -0800, ffolkes1911 wrote:
> > Hi,
> > 
> > we've been using `ser2net` v4.5 and connecting with python serial code for some time, everything was working fine. Today I setup another computer, but during this setup I pulled latest `ser2net` version 4.6. Using this latest version when I try to connect using python telnet, I get error:  
> > ```
> >  File ".../src/pts_packages/serial_operations.py", line 58, in serial_connect
> >     self.CONN = serial.serial_for_url(
> >   File ".../.ptsenv/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
> >     instance.open()
> >   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 493, in open
> >     self.reset_input_buffer()
> >   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 647, in reset_input_buffer
> >     self.rfc2217_send_purge(PURGE_RECEIVE_BUFFER)
> >   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 876, in rfc2217_send_purge
> >     item.wait(self._network_timeout)  # wait for acknowledge from the server
> >   File ".../.ptsenv/lib/python3.10/site-packages/serial/rfc2217.py", line 362, in wait
> >     raise SerialException("timeout while waiting for option {!r}".format(self.name))
> > serial.serialutil.SerialException: timeout while waiting for option 'purge'
> > ```
> 
> What is the gensio version where it works?  The problem is probably not
> in ser2net, it's probably in the gensio library.

Oh wait, I see the error.  Can you test a fix?

-corey

**Comment by ffolkes1911** [comment] 2024-02-01 16:30
I only reverted ser2net version, gensio stayed the same (2.8.2).  
I need my work computer to check, so I can try tomorrow.

**Comment by cminyard** [comment] 2024-02-02 02:50
On Thu, Feb 01, 2024 at 08:30:39AM -0800, ffolkes1911 wrote:
> I only reverted ser2net version, gensio stayed the same (2.8.2).  
> I need my work computer to check, so I can try tomorrow.

I just pushed up something to fix this, and I added the missing test
that let this slip through.

It's in git.  I can also send a patch, if you like, to test.

Thanks,

-corey

**Comment by cminyard** [comment] 2024-02-02 02:51
On Thu, Feb 01, 2024 at 08:50:49PM -0600, Corey Minyard wrote:
> On Thu, Feb 01, 2024 at 08:30:39AM -0800, ffolkes1911 wrote:
> > I only reverted ser2net version, gensio stayed the same (2.8.2).  
> > I need my work computer to check, so I can try tomorrow.
> 
> I just pushed up something to fix this, and I added the missing test
> that let this slip through.
> 
> It's in git.  I can also send a patch, if you like, to test.

Oh, and I forgot to say that the change is in ser2net, not gensio.

> 
> Thanks,
> 
> -corey

**Comment by ffolkes1911** [comment] 2024-02-02 06:33
Tried with latest `ser2net` commit [a369585](https://github.com/cminyard/ser2net/commit/a3695852615dd88424ca48141d0252ed73786eea) and same gensio version as before, I can connect using our python code and manually using CLI - issue seems resolved.  

Thank you for the quick response and fix. Issue can be closed?

**Comment by cminyard** [comment] 2024-02-02 13:38
On Thu, Feb 01, 2024 at 10:33:17PM -0800, ffolkes1911 wrote:
> Tried with latest `ser2net` commit [a369585](https://github.com/cminyard/ser2net/commit/a3695852615dd88424ca48141d0252ed73786eea) and same gensio version as before, I can connect using our python code and manually using CLI - issue seems resolved.  
> 
> Thank you for the quick response and fix. Issue can be closed?

Yes, you can close the issue, I believe it's fixed.  It was a
combination of a copy and paste error and a missing test.

Thanks for reporting.

**Closed** 2024-02-02 17:38 UTC
